version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 2
    versioning-strategy: increase
    ignore:
      - dependency-name: typescript
        update-types:
          - version-update:semver-minor
          - version-update:semver-major
      - dependency-name: "@types/node"
        update-types:
          - version-update:semver-major
    groups:
      non-major:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 1
    groups:
      actions:
        patterns:
          - "*"
