version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    versioning-strategy: "increase"
    ignore:
      - dependency-name: "typescript"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-major"
      - dependency-name: "@types/node"
        update-types:
          - "version-update:semver-major"
    groups:
      eslint:
        patterns:
          - "eslint*"
          - "prettier"
          - "@*/prettier*"
          - "@*/eslint*"
      testing:
        patterns:
          - "vitest"
          - "@vitest/*"
          - "playwright"
          - "testing-library/*"
          - "happy-dom"
          - "msw"
      "tanstack-start":
        patterns:
          - "@tanstack/start"
          - "@tanstack/react-router"
          - "@tanstack/react-router-with-query"
          - "@tanstack/router-devtools"
      "dev-deps":
        dependency-type: "development"
      "prod-deps":
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    groups:
      actions:
        patterns:
          - "*"
