app:popcorn.fyi:
  - changed-files:
      - any-glob-to-any-file: ["apps/web/**"]

lib:api-clients:
  - changed-files:
      - any-glob-to-any-file: ["libs/api-clients/**"]

lib:db:
  - changed-files:
      - any-glob-to-any-file: ["libs/db/**"]

lib:ui:
  - changed-files:
      - any-glob-to-any-file: ["libs/ui/**"]

lib:utils:
  - changed-files:
      - any-glob-to-any-file: ["libs/utils/**"]

config:eslint:
  - changed-files:
      - any-glob-to-any-file: ["configs/eslint/**"]

config:tailwind:
  - changed-files:
      - any-glob-to-any-file: ["configs/tailwind/**"]

config:typescript:
  - changed-files:
      - any-glob-to-any-file: ["configs/ts/**"]
