packages:
  - "apps/*"
  - "libs/*"
  - "configs/*"
onlyBuiltDependencies:
  - "@clerk/shared"
  - "@parcel/watcher"
  - "@vercel/speed-insights"
  - "bufferutil"
  - "esbuild"
  - "lefthook"
  - "msw"
