autoInstallPeers: false

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@tailwindcss/oxide"
  - "@vercel/speed-insights"
  - bufferutil
  - esbuild
  - lefthook
  - msw
  - oxc-resolver
  - unrs-resolver

savePrefix: ""

overrides:
  vite: "8.0.8"

cleanupUnusedCatalogs: true
