autoInstallPeers: false

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@tailwindcss/oxide"
  - "@vercel/speed-insights"
  - bufferutil
  - esbuild
  - lefthook
  - msw
  - unrs-resolver

patchedDependencies:
  openapi-fetch@0.14.0: patches/openapi-fetch@0.14.0.patch

savePrefix: ""
