packages:
  - apps/*
  - libs/*
  - configs/*

autoInstallPeers: false

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@tailwindcss/oxide"
  - "@vercel/speed-insights"
  - bufferutil
  - esbuild
  - lefthook
  - msw
  - unrs-resolver

patchedDependencies:
  openapi-fetch@0.13.4: patches/openapi-fetch@0.13.4.patch

savePrefix: ""
