/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Wikidata entity by ID
         * @description Fetch entity data from Wikidata using the entity ID.
         */
        get: {
            parameters: {
                query: {
                    /** @description The API action to perform (always 'wbgetentities' for entity fetching). */
                    action: string;
                    /** @description The Wikidata entity ID (e.g., Q42). */
                    ids: string;
                    /** @description The response format (set to 'json'). */
                    format: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response with entity data. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            entities?: {
                                [key: string]: {
                                    id?: string;
                                    sitelinks?: {
                                        [key: string]: {
                                            site?: string;
                                            title?: string;
                                            url?: string;
                                        };
                                    };
                                };
                            };
                        };
                    };
                };
                /** @description Bad request, missing or invalid parameters. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Entity not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
