/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSearchRouteImport } from './routes/_layout/search'
import { Route as LayoutTvShowsTopRatedRouteImport } from './routes/_layout/tv-shows.top-rated'
import { Route as LayoutTvShowsPopularRouteImport } from './routes/_layout/tv-shows.popular'
import { Route as LayoutTvShowsIdRouteImport } from './routes/_layout/tv-shows.$id'
import { Route as LayoutTrendingTvShowsRouteImport } from './routes/_layout/trending.tv-shows'
import { Route as LayoutTrendingPeopleRouteImport } from './routes/_layout/trending.people'
import { Route as LayoutTrendingMoviesRouteImport } from './routes/_layout/trending.movies'
import { Route as LayoutPeoplePopularRouteImport } from './routes/_layout/people.popular'
import { Route as LayoutPeopleIdRouteImport } from './routes/_layout/people.$id'
import { Route as LayoutMoviesTopRatedRouteImport } from './routes/_layout/movies.top-rated'
import { Route as LayoutMoviesPopularRouteImport } from './routes/_layout/movies.popular'
import { Route as LayoutMoviesIdRouteImport } from './routes/_layout/movies.$id'
import { Route as LayoutTvShowsIdIndexRouteImport } from './routes/_layout/tv-shows.$id.index'
import { Route as LayoutPeopleIdIndexRouteImport } from './routes/_layout/people.$id.index'
import { Route as LayoutMoviesIdIndexRouteImport } from './routes/_layout/movies.$id.index'
import { Route as LayoutTvShowsDiscoverLayoutRouteImport } from './routes/_layout/tv-shows.discover._layout'
import { Route as LayoutTvShowsIdWatchRouteImport } from './routes/_layout/tv-shows.$id.watch'
import { Route as LayoutTvShowsIdTrailerRouteImport } from './routes/_layout/tv-shows.$id.trailer'
import { Route as LayoutTvShowsIdSimilarRouteImport } from './routes/_layout/tv-shows.$id.similar'
import { Route as LayoutTvShowsIdCreditsRouteImport } from './routes/_layout/tv-shows.$id.credits'
import { Route as LayoutPeopleIdCreditsRouteImport } from './routes/_layout/people.$id.credits'
import { Route as LayoutMoviesDiscoverLayoutRouteImport } from './routes/_layout/movies.discover._layout'
import { Route as LayoutMoviesIdWatchRouteImport } from './routes/_layout/movies.$id.watch'
import { Route as LayoutMoviesIdTrailerRouteImport } from './routes/_layout/movies.$id.trailer'
import { Route as LayoutMoviesIdSimilarRouteImport } from './routes/_layout/movies.$id.similar'
import { Route as LayoutMoviesIdCreditsRouteImport } from './routes/_layout/movies.$id.credits'
import { Route as LayoutTvShowsDiscoverLayoutIndexRouteImport } from './routes/_layout/tv-shows.discover._layout.index'
import { Route as LayoutMoviesDiscoverLayoutIndexRouteImport } from './routes/_layout/movies.discover._layout.index'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSearchRoute = LayoutSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTvShowsTopRatedRoute = LayoutTvShowsTopRatedRouteImport.update({
  id: '/tv-shows/top-rated',
  path: '/tv-shows/top-rated',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTvShowsPopularRoute = LayoutTvShowsPopularRouteImport.update({
  id: '/tv-shows/popular',
  path: '/tv-shows/popular',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTvShowsIdRoute = LayoutTvShowsIdRouteImport.update({
  id: '/tv-shows/$id',
  path: '/tv-shows/$id',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTrendingTvShowsRoute = LayoutTrendingTvShowsRouteImport.update({
  id: '/trending/tv-shows',
  path: '/trending/tv-shows',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTrendingPeopleRoute = LayoutTrendingPeopleRouteImport.update({
  id: '/trending/people',
  path: '/trending/people',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTrendingMoviesRoute = LayoutTrendingMoviesRouteImport.update({
  id: '/trending/movies',
  path: '/trending/movies',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPeoplePopularRoute = LayoutPeoplePopularRouteImport.update({
  id: '/people/popular',
  path: '/people/popular',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPeopleIdRoute = LayoutPeopleIdRouteImport.update({
  id: '/people/$id',
  path: '/people/$id',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMoviesTopRatedRoute = LayoutMoviesTopRatedRouteImport.update({
  id: '/movies/top-rated',
  path: '/movies/top-rated',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMoviesPopularRoute = LayoutMoviesPopularRouteImport.update({
  id: '/movies/popular',
  path: '/movies/popular',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMoviesIdRoute = LayoutMoviesIdRouteImport.update({
  id: '/movies/$id',
  path: '/movies/$id',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTvShowsIdIndexRoute = LayoutTvShowsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutTvShowsIdRoute,
} as any)
const LayoutPeopleIdIndexRoute = LayoutPeopleIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutPeopleIdRoute,
} as any)
const LayoutMoviesIdIndexRoute = LayoutMoviesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutMoviesIdRoute,
} as any)
const LayoutTvShowsDiscoverLayoutRoute =
  LayoutTvShowsDiscoverLayoutRouteImport.update({
    id: '/_layout/tv-shows/discover/_layout',
    path: '/tv-shows/discover',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutTvShowsIdWatchRoute = LayoutTvShowsIdWatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => LayoutTvShowsIdRoute,
} as any)
const LayoutTvShowsIdTrailerRoute = LayoutTvShowsIdTrailerRouteImport.update({
  id: '/trailer',
  path: '/trailer',
  getParentRoute: () => LayoutTvShowsIdRoute,
} as any)
const LayoutTvShowsIdSimilarRoute = LayoutTvShowsIdSimilarRouteImport.update({
  id: '/similar',
  path: '/similar',
  getParentRoute: () => LayoutTvShowsIdRoute,
} as any)
const LayoutTvShowsIdCreditsRoute = LayoutTvShowsIdCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => LayoutTvShowsIdRoute,
} as any)
const LayoutPeopleIdCreditsRoute = LayoutPeopleIdCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => LayoutPeopleIdRoute,
} as any)
const LayoutMoviesDiscoverLayoutRoute =
  LayoutMoviesDiscoverLayoutRouteImport.update({
    id: '/_layout/movies/discover/_layout',
    path: '/movies/discover',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutMoviesIdWatchRoute = LayoutMoviesIdWatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => LayoutMoviesIdRoute,
} as any)
const LayoutMoviesIdTrailerRoute = LayoutMoviesIdTrailerRouteImport.update({
  id: '/trailer',
  path: '/trailer',
  getParentRoute: () => LayoutMoviesIdRoute,
} as any)
const LayoutMoviesIdSimilarRoute = LayoutMoviesIdSimilarRouteImport.update({
  id: '/similar',
  path: '/similar',
  getParentRoute: () => LayoutMoviesIdRoute,
} as any)
const LayoutMoviesIdCreditsRoute = LayoutMoviesIdCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => LayoutMoviesIdRoute,
} as any)
const LayoutTvShowsDiscoverLayoutIndexRoute =
  LayoutTvShowsDiscoverLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutTvShowsDiscoverLayoutRoute,
  } as any)
const LayoutMoviesDiscoverLayoutIndexRoute =
  LayoutMoviesDiscoverLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutMoviesDiscoverLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/search': typeof LayoutSearchRoute
  '/': typeof LayoutIndexRoute
  '/movies/$id': typeof LayoutMoviesIdRouteWithChildren
  '/movies/popular': typeof LayoutMoviesPopularRoute
  '/movies/top-rated': typeof LayoutMoviesTopRatedRoute
  '/people/$id': typeof LayoutPeopleIdRouteWithChildren
  '/people/popular': typeof LayoutPeoplePopularRoute
  '/trending/movies': typeof LayoutTrendingMoviesRoute
  '/trending/people': typeof LayoutTrendingPeopleRoute
  '/trending/tv-shows': typeof LayoutTrendingTvShowsRoute
  '/tv-shows/$id': typeof LayoutTvShowsIdRouteWithChildren
  '/tv-shows/popular': typeof LayoutTvShowsPopularRoute
  '/tv-shows/top-rated': typeof LayoutTvShowsTopRatedRoute
  '/movies/$id/credits': typeof LayoutMoviesIdCreditsRoute
  '/movies/$id/similar': typeof LayoutMoviesIdSimilarRoute
  '/movies/$id/trailer': typeof LayoutMoviesIdTrailerRoute
  '/movies/$id/watch': typeof LayoutMoviesIdWatchRoute
  '/movies/discover': typeof LayoutMoviesDiscoverLayoutRouteWithChildren
  '/people/$id/credits': typeof LayoutPeopleIdCreditsRoute
  '/tv-shows/$id/credits': typeof LayoutTvShowsIdCreditsRoute
  '/tv-shows/$id/similar': typeof LayoutTvShowsIdSimilarRoute
  '/tv-shows/$id/trailer': typeof LayoutTvShowsIdTrailerRoute
  '/tv-shows/$id/watch': typeof LayoutTvShowsIdWatchRoute
  '/tv-shows/discover': typeof LayoutTvShowsDiscoverLayoutRouteWithChildren
  '/movies/$id/': typeof LayoutMoviesIdIndexRoute
  '/people/$id/': typeof LayoutPeopleIdIndexRoute
  '/tv-shows/$id/': typeof LayoutTvShowsIdIndexRoute
  '/movies/discover/': typeof LayoutMoviesDiscoverLayoutIndexRoute
  '/tv-shows/discover/': typeof LayoutTvShowsDiscoverLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/search': typeof LayoutSearchRoute
  '/': typeof LayoutIndexRoute
  '/movies/popular': typeof LayoutMoviesPopularRoute
  '/movies/top-rated': typeof LayoutMoviesTopRatedRoute
  '/people/popular': typeof LayoutPeoplePopularRoute
  '/trending/movies': typeof LayoutTrendingMoviesRoute
  '/trending/people': typeof LayoutTrendingPeopleRoute
  '/trending/tv-shows': typeof LayoutTrendingTvShowsRoute
  '/tv-shows/popular': typeof LayoutTvShowsPopularRoute
  '/tv-shows/top-rated': typeof LayoutTvShowsTopRatedRoute
  '/movies/$id/credits': typeof LayoutMoviesIdCreditsRoute
  '/movies/$id/similar': typeof LayoutMoviesIdSimilarRoute
  '/movies/$id/trailer': typeof LayoutMoviesIdTrailerRoute
  '/movies/$id/watch': typeof LayoutMoviesIdWatchRoute
  '/people/$id/credits': typeof LayoutPeopleIdCreditsRoute
  '/tv-shows/$id/credits': typeof LayoutTvShowsIdCreditsRoute
  '/tv-shows/$id/similar': typeof LayoutTvShowsIdSimilarRoute
  '/tv-shows/$id/trailer': typeof LayoutTvShowsIdTrailerRoute
  '/tv-shows/$id/watch': typeof LayoutTvShowsIdWatchRoute
  '/movies/$id': typeof LayoutMoviesIdIndexRoute
  '/people/$id': typeof LayoutPeopleIdIndexRoute
  '/tv-shows/$id': typeof LayoutTvShowsIdIndexRoute
  '/movies/discover': typeof LayoutMoviesDiscoverLayoutIndexRoute
  '/tv-shows/discover': typeof LayoutTvShowsDiscoverLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/search': typeof LayoutSearchRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/movies/$id': typeof LayoutMoviesIdRouteWithChildren
  '/_layout/movies/popular': typeof LayoutMoviesPopularRoute
  '/_layout/movies/top-rated': typeof LayoutMoviesTopRatedRoute
  '/_layout/people/$id': typeof LayoutPeopleIdRouteWithChildren
  '/_layout/people/popular': typeof LayoutPeoplePopularRoute
  '/_layout/trending/movies': typeof LayoutTrendingMoviesRoute
  '/_layout/trending/people': typeof LayoutTrendingPeopleRoute
  '/_layout/trending/tv-shows': typeof LayoutTrendingTvShowsRoute
  '/_layout/tv-shows/$id': typeof LayoutTvShowsIdRouteWithChildren
  '/_layout/tv-shows/popular': typeof LayoutTvShowsPopularRoute
  '/_layout/tv-shows/top-rated': typeof LayoutTvShowsTopRatedRoute
  '/_layout/movies/$id/credits': typeof LayoutMoviesIdCreditsRoute
  '/_layout/movies/$id/similar': typeof LayoutMoviesIdSimilarRoute
  '/_layout/movies/$id/trailer': typeof LayoutMoviesIdTrailerRoute
  '/_layout/movies/$id/watch': typeof LayoutMoviesIdWatchRoute
  '/_layout/movies/discover/_layout': typeof LayoutMoviesDiscoverLayoutRouteWithChildren
  '/_layout/people/$id/credits': typeof LayoutPeopleIdCreditsRoute
  '/_layout/tv-shows/$id/credits': typeof LayoutTvShowsIdCreditsRoute
  '/_layout/tv-shows/$id/similar': typeof LayoutTvShowsIdSimilarRoute
  '/_layout/tv-shows/$id/trailer': typeof LayoutTvShowsIdTrailerRoute
  '/_layout/tv-shows/$id/watch': typeof LayoutTvShowsIdWatchRoute
  '/_layout/tv-shows/discover/_layout': typeof LayoutTvShowsDiscoverLayoutRouteWithChildren
  '/_layout/movies/$id/': typeof LayoutMoviesIdIndexRoute
  '/_layout/people/$id/': typeof LayoutPeopleIdIndexRoute
  '/_layout/tv-shows/$id/': typeof LayoutTvShowsIdIndexRoute
  '/_layout/movies/discover/_layout/': typeof LayoutMoviesDiscoverLayoutIndexRoute
  '/_layout/tv-shows/discover/_layout/': typeof LayoutTvShowsDiscoverLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/search'
    | '/'
    | '/movies/$id'
    | '/movies/popular'
    | '/movies/top-rated'
    | '/people/$id'
    | '/people/popular'
    | '/trending/movies'
    | '/trending/people'
    | '/trending/tv-shows'
    | '/tv-shows/$id'
    | '/tv-shows/popular'
    | '/tv-shows/top-rated'
    | '/movies/$id/credits'
    | '/movies/$id/similar'
    | '/movies/$id/trailer'
    | '/movies/$id/watch'
    | '/movies/discover'
    | '/people/$id/credits'
    | '/tv-shows/$id/credits'
    | '/tv-shows/$id/similar'
    | '/tv-shows/$id/trailer'
    | '/tv-shows/$id/watch'
    | '/tv-shows/discover'
    | '/movies/$id/'
    | '/people/$id/'
    | '/tv-shows/$id/'
    | '/movies/discover/'
    | '/tv-shows/discover/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/search'
    | '/'
    | '/movies/popular'
    | '/movies/top-rated'
    | '/people/popular'
    | '/trending/movies'
    | '/trending/people'
    | '/trending/tv-shows'
    | '/tv-shows/popular'
    | '/tv-shows/top-rated'
    | '/movies/$id/credits'
    | '/movies/$id/similar'
    | '/movies/$id/trailer'
    | '/movies/$id/watch'
    | '/people/$id/credits'
    | '/tv-shows/$id/credits'
    | '/tv-shows/$id/similar'
    | '/tv-shows/$id/trailer'
    | '/tv-shows/$id/watch'
    | '/movies/$id'
    | '/people/$id'
    | '/tv-shows/$id'
    | '/movies/discover'
    | '/tv-shows/discover'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/search'
    | '/_layout/'
    | '/_layout/movies/$id'
    | '/_layout/movies/popular'
    | '/_layout/movies/top-rated'
    | '/_layout/people/$id'
    | '/_layout/people/popular'
    | '/_layout/trending/movies'
    | '/_layout/trending/people'
    | '/_layout/trending/tv-shows'
    | '/_layout/tv-shows/$id'
    | '/_layout/tv-shows/popular'
    | '/_layout/tv-shows/top-rated'
    | '/_layout/movies/$id/credits'
    | '/_layout/movies/$id/similar'
    | '/_layout/movies/$id/trailer'
    | '/_layout/movies/$id/watch'
    | '/_layout/movies/discover/_layout'
    | '/_layout/people/$id/credits'
    | '/_layout/tv-shows/$id/credits'
    | '/_layout/tv-shows/$id/similar'
    | '/_layout/tv-shows/$id/trailer'
    | '/_layout/tv-shows/$id/watch'
    | '/_layout/tv-shows/discover/_layout'
    | '/_layout/movies/$id/'
    | '/_layout/people/$id/'
    | '/_layout/tv-shows/$id/'
    | '/_layout/movies/discover/_layout/'
    | '/_layout/tv-shows/discover/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/search': {
      id: '/_layout/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof LayoutSearchRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tv-shows/top-rated': {
      id: '/_layout/tv-shows/top-rated'
      path: '/tv-shows/top-rated'
      fullPath: '/tv-shows/top-rated'
      preLoaderRoute: typeof LayoutTvShowsTopRatedRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tv-shows/popular': {
      id: '/_layout/tv-shows/popular'
      path: '/tv-shows/popular'
      fullPath: '/tv-shows/popular'
      preLoaderRoute: typeof LayoutTvShowsPopularRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tv-shows/$id': {
      id: '/_layout/tv-shows/$id'
      path: '/tv-shows/$id'
      fullPath: '/tv-shows/$id'
      preLoaderRoute: typeof LayoutTvShowsIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/trending/tv-shows': {
      id: '/_layout/trending/tv-shows'
      path: '/trending/tv-shows'
      fullPath: '/trending/tv-shows'
      preLoaderRoute: typeof LayoutTrendingTvShowsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/trending/people': {
      id: '/_layout/trending/people'
      path: '/trending/people'
      fullPath: '/trending/people'
      preLoaderRoute: typeof LayoutTrendingPeopleRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/trending/movies': {
      id: '/_layout/trending/movies'
      path: '/trending/movies'
      fullPath: '/trending/movies'
      preLoaderRoute: typeof LayoutTrendingMoviesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/people/popular': {
      id: '/_layout/people/popular'
      path: '/people/popular'
      fullPath: '/people/popular'
      preLoaderRoute: typeof LayoutPeoplePopularRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/people/$id': {
      id: '/_layout/people/$id'
      path: '/people/$id'
      fullPath: '/people/$id'
      preLoaderRoute: typeof LayoutPeopleIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/movies/top-rated': {
      id: '/_layout/movies/top-rated'
      path: '/movies/top-rated'
      fullPath: '/movies/top-rated'
      preLoaderRoute: typeof LayoutMoviesTopRatedRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/movies/popular': {
      id: '/_layout/movies/popular'
      path: '/movies/popular'
      fullPath: '/movies/popular'
      preLoaderRoute: typeof LayoutMoviesPopularRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/movies/$id': {
      id: '/_layout/movies/$id'
      path: '/movies/$id'
      fullPath: '/movies/$id'
      preLoaderRoute: typeof LayoutMoviesIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tv-shows/$id/': {
      id: '/_layout/tv-shows/$id/'
      path: '/'
      fullPath: '/tv-shows/$id/'
      preLoaderRoute: typeof LayoutTvShowsIdIndexRouteImport
      parentRoute: typeof LayoutTvShowsIdRoute
    }
    '/_layout/people/$id/': {
      id: '/_layout/people/$id/'
      path: '/'
      fullPath: '/people/$id/'
      preLoaderRoute: typeof LayoutPeopleIdIndexRouteImport
      parentRoute: typeof LayoutPeopleIdRoute
    }
    '/_layout/movies/$id/': {
      id: '/_layout/movies/$id/'
      path: '/'
      fullPath: '/movies/$id/'
      preLoaderRoute: typeof LayoutMoviesIdIndexRouteImport
      parentRoute: typeof LayoutMoviesIdRoute
    }
    '/_layout/tv-shows/discover/_layout': {
      id: '/_layout/tv-shows/discover/_layout'
      path: '/tv-shows/discover'
      fullPath: '/tv-shows/discover'
      preLoaderRoute: typeof LayoutTvShowsDiscoverLayoutRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tv-shows/$id/watch': {
      id: '/_layout/tv-shows/$id/watch'
      path: '/watch'
      fullPath: '/tv-shows/$id/watch'
      preLoaderRoute: typeof LayoutTvShowsIdWatchRouteImport
      parentRoute: typeof LayoutTvShowsIdRoute
    }
    '/_layout/tv-shows/$id/trailer': {
      id: '/_layout/tv-shows/$id/trailer'
      path: '/trailer'
      fullPath: '/tv-shows/$id/trailer'
      preLoaderRoute: typeof LayoutTvShowsIdTrailerRouteImport
      parentRoute: typeof LayoutTvShowsIdRoute
    }
    '/_layout/tv-shows/$id/similar': {
      id: '/_layout/tv-shows/$id/similar'
      path: '/similar'
      fullPath: '/tv-shows/$id/similar'
      preLoaderRoute: typeof LayoutTvShowsIdSimilarRouteImport
      parentRoute: typeof LayoutTvShowsIdRoute
    }
    '/_layout/tv-shows/$id/credits': {
      id: '/_layout/tv-shows/$id/credits'
      path: '/credits'
      fullPath: '/tv-shows/$id/credits'
      preLoaderRoute: typeof LayoutTvShowsIdCreditsRouteImport
      parentRoute: typeof LayoutTvShowsIdRoute
    }
    '/_layout/people/$id/credits': {
      id: '/_layout/people/$id/credits'
      path: '/credits'
      fullPath: '/people/$id/credits'
      preLoaderRoute: typeof LayoutPeopleIdCreditsRouteImport
      parentRoute: typeof LayoutPeopleIdRoute
    }
    '/_layout/movies/discover/_layout': {
      id: '/_layout/movies/discover/_layout'
      path: '/movies/discover'
      fullPath: '/movies/discover'
      preLoaderRoute: typeof LayoutMoviesDiscoverLayoutRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/movies/$id/watch': {
      id: '/_layout/movies/$id/watch'
      path: '/watch'
      fullPath: '/movies/$id/watch'
      preLoaderRoute: typeof LayoutMoviesIdWatchRouteImport
      parentRoute: typeof LayoutMoviesIdRoute
    }
    '/_layout/movies/$id/trailer': {
      id: '/_layout/movies/$id/trailer'
      path: '/trailer'
      fullPath: '/movies/$id/trailer'
      preLoaderRoute: typeof LayoutMoviesIdTrailerRouteImport
      parentRoute: typeof LayoutMoviesIdRoute
    }
    '/_layout/movies/$id/similar': {
      id: '/_layout/movies/$id/similar'
      path: '/similar'
      fullPath: '/movies/$id/similar'
      preLoaderRoute: typeof LayoutMoviesIdSimilarRouteImport
      parentRoute: typeof LayoutMoviesIdRoute
    }
    '/_layout/movies/$id/credits': {
      id: '/_layout/movies/$id/credits'
      path: '/credits'
      fullPath: '/movies/$id/credits'
      preLoaderRoute: typeof LayoutMoviesIdCreditsRouteImport
      parentRoute: typeof LayoutMoviesIdRoute
    }
    '/_layout/tv-shows/discover/_layout/': {
      id: '/_layout/tv-shows/discover/_layout/'
      path: '/'
      fullPath: '/tv-shows/discover/'
      preLoaderRoute: typeof LayoutTvShowsDiscoverLayoutIndexRouteImport
      parentRoute: typeof LayoutTvShowsDiscoverLayoutRoute
    }
    '/_layout/movies/discover/_layout/': {
      id: '/_layout/movies/discover/_layout/'
      path: '/'
      fullPath: '/movies/discover/'
      preLoaderRoute: typeof LayoutMoviesDiscoverLayoutIndexRouteImport
      parentRoute: typeof LayoutMoviesDiscoverLayoutRoute
    }
  }
}

interface LayoutMoviesIdRouteChildren {
  LayoutMoviesIdCreditsRoute: typeof LayoutMoviesIdCreditsRoute
  LayoutMoviesIdSimilarRoute: typeof LayoutMoviesIdSimilarRoute
  LayoutMoviesIdTrailerRoute: typeof LayoutMoviesIdTrailerRoute
  LayoutMoviesIdWatchRoute: typeof LayoutMoviesIdWatchRoute
  LayoutMoviesIdIndexRoute: typeof LayoutMoviesIdIndexRoute
}

const LayoutMoviesIdRouteChildren: LayoutMoviesIdRouteChildren = {
  LayoutMoviesIdCreditsRoute: LayoutMoviesIdCreditsRoute,
  LayoutMoviesIdSimilarRoute: LayoutMoviesIdSimilarRoute,
  LayoutMoviesIdTrailerRoute: LayoutMoviesIdTrailerRoute,
  LayoutMoviesIdWatchRoute: LayoutMoviesIdWatchRoute,
  LayoutMoviesIdIndexRoute: LayoutMoviesIdIndexRoute,
}

const LayoutMoviesIdRouteWithChildren = LayoutMoviesIdRoute._addFileChildren(
  LayoutMoviesIdRouteChildren,
)

interface LayoutPeopleIdRouteChildren {
  LayoutPeopleIdCreditsRoute: typeof LayoutPeopleIdCreditsRoute
  LayoutPeopleIdIndexRoute: typeof LayoutPeopleIdIndexRoute
}

const LayoutPeopleIdRouteChildren: LayoutPeopleIdRouteChildren = {
  LayoutPeopleIdCreditsRoute: LayoutPeopleIdCreditsRoute,
  LayoutPeopleIdIndexRoute: LayoutPeopleIdIndexRoute,
}

const LayoutPeopleIdRouteWithChildren = LayoutPeopleIdRoute._addFileChildren(
  LayoutPeopleIdRouteChildren,
)

interface LayoutTvShowsIdRouteChildren {
  LayoutTvShowsIdCreditsRoute: typeof LayoutTvShowsIdCreditsRoute
  LayoutTvShowsIdSimilarRoute: typeof LayoutTvShowsIdSimilarRoute
  LayoutTvShowsIdTrailerRoute: typeof LayoutTvShowsIdTrailerRoute
  LayoutTvShowsIdWatchRoute: typeof LayoutTvShowsIdWatchRoute
  LayoutTvShowsIdIndexRoute: typeof LayoutTvShowsIdIndexRoute
}

const LayoutTvShowsIdRouteChildren: LayoutTvShowsIdRouteChildren = {
  LayoutTvShowsIdCreditsRoute: LayoutTvShowsIdCreditsRoute,
  LayoutTvShowsIdSimilarRoute: LayoutTvShowsIdSimilarRoute,
  LayoutTvShowsIdTrailerRoute: LayoutTvShowsIdTrailerRoute,
  LayoutTvShowsIdWatchRoute: LayoutTvShowsIdWatchRoute,
  LayoutTvShowsIdIndexRoute: LayoutTvShowsIdIndexRoute,
}

const LayoutTvShowsIdRouteWithChildren = LayoutTvShowsIdRoute._addFileChildren(
  LayoutTvShowsIdRouteChildren,
)

interface LayoutMoviesDiscoverLayoutRouteChildren {
  LayoutMoviesDiscoverLayoutIndexRoute: typeof LayoutMoviesDiscoverLayoutIndexRoute
}

const LayoutMoviesDiscoverLayoutRouteChildren: LayoutMoviesDiscoverLayoutRouteChildren =
  {
    LayoutMoviesDiscoverLayoutIndexRoute: LayoutMoviesDiscoverLayoutIndexRoute,
  }

const LayoutMoviesDiscoverLayoutRouteWithChildren =
  LayoutMoviesDiscoverLayoutRoute._addFileChildren(
    LayoutMoviesDiscoverLayoutRouteChildren,
  )

interface LayoutTvShowsDiscoverLayoutRouteChildren {
  LayoutTvShowsDiscoverLayoutIndexRoute: typeof LayoutTvShowsDiscoverLayoutIndexRoute
}

const LayoutTvShowsDiscoverLayoutRouteChildren: LayoutTvShowsDiscoverLayoutRouteChildren =
  {
    LayoutTvShowsDiscoverLayoutIndexRoute:
      LayoutTvShowsDiscoverLayoutIndexRoute,
  }

const LayoutTvShowsDiscoverLayoutRouteWithChildren =
  LayoutTvShowsDiscoverLayoutRoute._addFileChildren(
    LayoutTvShowsDiscoverLayoutRouteChildren,
  )

interface LayoutRouteChildren {
  LayoutSearchRoute: typeof LayoutSearchRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutMoviesIdRoute: typeof LayoutMoviesIdRouteWithChildren
  LayoutMoviesPopularRoute: typeof LayoutMoviesPopularRoute
  LayoutMoviesTopRatedRoute: typeof LayoutMoviesTopRatedRoute
  LayoutPeopleIdRoute: typeof LayoutPeopleIdRouteWithChildren
  LayoutPeoplePopularRoute: typeof LayoutPeoplePopularRoute
  LayoutTrendingMoviesRoute: typeof LayoutTrendingMoviesRoute
  LayoutTrendingPeopleRoute: typeof LayoutTrendingPeopleRoute
  LayoutTrendingTvShowsRoute: typeof LayoutTrendingTvShowsRoute
  LayoutTvShowsIdRoute: typeof LayoutTvShowsIdRouteWithChildren
  LayoutTvShowsPopularRoute: typeof LayoutTvShowsPopularRoute
  LayoutTvShowsTopRatedRoute: typeof LayoutTvShowsTopRatedRoute
  LayoutMoviesDiscoverLayoutRoute: typeof LayoutMoviesDiscoverLayoutRouteWithChildren
  LayoutTvShowsDiscoverLayoutRoute: typeof LayoutTvShowsDiscoverLayoutRouteWithChildren
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutSearchRoute: LayoutSearchRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutMoviesIdRoute: LayoutMoviesIdRouteWithChildren,
  LayoutMoviesPopularRoute: LayoutMoviesPopularRoute,
  LayoutMoviesTopRatedRoute: LayoutMoviesTopRatedRoute,
  LayoutPeopleIdRoute: LayoutPeopleIdRouteWithChildren,
  LayoutPeoplePopularRoute: LayoutPeoplePopularRoute,
  LayoutTrendingMoviesRoute: LayoutTrendingMoviesRoute,
  LayoutTrendingPeopleRoute: LayoutTrendingPeopleRoute,
  LayoutTrendingTvShowsRoute: LayoutTrendingTvShowsRoute,
  LayoutTvShowsIdRoute: LayoutTvShowsIdRouteWithChildren,
  LayoutTvShowsPopularRoute: LayoutTvShowsPopularRoute,
  LayoutTvShowsTopRatedRoute: LayoutTvShowsTopRatedRoute,
  LayoutMoviesDiscoverLayoutRoute: LayoutMoviesDiscoverLayoutRouteWithChildren,
  LayoutTvShowsDiscoverLayoutRoute:
    LayoutTvShowsDiscoverLayoutRouteWithChildren,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
